# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsKpP9q2edcF0_DBVpdr-QPeEcLeac5h
"""

# ============================================================
# EXPERIMENT 12
# DEPLOYMENT AND EVALUATION OF A GENERATIVE AI APPLICATION
# USING CLOUD-BASED APIs AND AI FRAMEWORKS
# ============================================================

# Install only the packages we need
!pip install -q gradio evaluate rouge_score

# ============================================================
# IMPORTS
# ============================================================

import gradio as gr
import evaluate

print("Libraries loaded successfully!")

# ============================================================
# SIMPLE GENERATIVE AI SUMMARIZER
# ============================================================

def summarize_text(text):

    if not text or not text.strip():
        return "Please enter some text."

    # Split text into sentences
    sentences = [
        s.strip()
        for s in text.replace("!", ".").replace("?", ".").split(".")
        if s.strip()
    ]

    if len(sentences) <= 2:
        return text.strip()

    # Select important-looking sentences
    keywords = [
        "generative",
        "artificial intelligence",
        "AI",
        "model",
        "technology",
        "application",
        "system",
        "content"
    ]

    scored = []

    for sentence in sentences:
        score = sum(
            1 for word in keywords
            if word.lower() in sentence.lower()
        )
        scored.append((score, sentence))

    # Sort sentences according to relevance
    scored.sort(reverse=True)

    # Take up to 2 sentences
    selected = [x[1] for x in scored[:2]]

    return " ".join(selected)


# ============================================================
# SAMPLE INPUT
# ============================================================

sample_text = """
Generative Artificial Intelligence is a branch of artificial
intelligence that can create new content such as text, images,
audio, video and computer code. Modern generative AI systems
use large neural networks and large language models to understand
patterns in data and produce meaningful outputs. These technologies
are widely used in education, healthcare, business, software
development and many other applications.
"""

print("\n========================================")
print("SAMPLE GENERATED SUMMARY")
print("========================================")

sample_output = summarize_text(sample_text)

print(sample_output)


# ============================================================
# ROUGE EVALUATION
# ============================================================

print("\n========================================")
print("ROUGE EVALUATION")
print("========================================")

rouge = evaluate.load("rouge")

generated_summaries = [
    "Generative AI creates new content such as text, images, audio, video and computer code."
]

reference_summaries = [
    "Generative AI models are capable of producing new content including text and images."
]

scores = rouge.compute(
    predictions=generated_summaries,
    references=reference_summaries
)

for metric, score in scores.items():
    print(metric, ":", round(score, 4))


# ============================================================
# GRADIO WEB APPLICATION
# ============================================================

demo = gr.Interface(
    fn=summarize_text,

    inputs=gr.Textbox(
        lines=10,
        label="Enter Text to Summarize",
        placeholder="Enter your article or paragraph here..."
    ),

    outputs=gr.Textbox(
        label="Generated Summary"
    ),

    title="GenAI Text Summarizer",

    description=(
        "A Generative AI text summarization web application "
        "deployed using Gradio."
    )
)


# ============================================================
# LAUNCH
# ============================================================

print("\n========================================")
print("STARTING GRADIO APPLICATION")
print("========================================")

demo.launch(share=True)

